### ISSUE TITLE
EFK stack for high availability cluster

### ISSUE THREAD

**Issue by laghao** [sadsfae/ansible-elk#18]
Hi,
I deployed ansible-efk (using fluentd) and it works perfectly, but now I want to expand this configuration to multi-nodes setup for high availability reasons. 
Is there any way to do it using this ansible-elk project ?

**Comment by canhduonguk** [comment]
I am not sure about Fluentd but I have the same need for a high availability cluster setup. My solution is that I split the setup scripts into three role groups: Elasticsearch, Logstash, Filebeat.

Since I use Filebeat for sending logs to Logstash servers. Thanks to the backpressure-sensitive protocol. it won't overload my Logstash servers, so high availability is maintained.

I hope this helps.

Best regards,
Canh

**Comment by sadsfae** [comment]
Thanks for filing this, I don't have any immediate plans to allow a multi-node setup yet for ansible-elk and provide the option for deploying on additional nodes.  I am going to leave this open and when time allows work towards getting this option in place.

**Comment by sadsfae** [comment]
I don't want to lead anyone on here that might expect multi-node support, I don't have the time to maintain the ELK/EFK outside of a single-node and multi 2.4 / 5.x+ (with focus being on 5.x) right now.  I am going to leave this open anyway but I don't expect to have time to expand beyond the single node at this time.

If this changes I'll update here.

**Comment by knechtionscoding** [comment]
@sadsfae I just submitted a PR for multi node elasticsearch support. I don't know enough about Fluentd to be able to support that, but if you can support the fluentd side, I can handle the ELK side. #49 is the PR for it.

**Comment by sadsfae** [comment]
I am folding this issue into the existing discussion and work here:

https://github.com/sadsfae/ansible-elk/issues/61
