### ISSUE TITLE
Consider adding curator

### ISSUE THREAD

**Issue by portante** [sadsfae/ansible-elk#4]
Have you considered adding curator?

See: https://review.openstack.org/gitweb?p=openstack/instack-undercloud.git;a=commitdiff;h=398f9180d27565ab54fbebe4989498129c1f9f38

**Comment by sadsfae** [comment]
Hey @portante that could work, the main focus of this was just to install ELK and filebeat and ongoing maintenance tools weren't in scope.  I will leave this open because I think it's a good idea and I do see it packaged in RPM so can definitely get this included.

https://www.elastic.co/guide/en/elasticsearch/client/curator/current/installation.html

**Comment by sadsfae** [comment]
hey @portante this is in place now via the following commit:
https://github.com/sadsfae/ansible-elk/commit/b8e0bcf06ad53b5c718e68ccd25f6295ed998c04

You need to set `es_curator_tool: install` in `install/group_vars/all.yml` to have curator installed via RPM now.
