### ISSUE TITLE
Elasticsearch data and log directory

### ISSUE THREAD

**Issue by yasirsharif** [sadsfae/ansible-elk#78]
Dear Will,
Why can't the data and logs be saved on /var directory instead of /usr/share directory.
Below lines from the file: install/roles/elasticsearch/tasks/main.yml

- name: Create log directory structure for ES
  file:
    path: /usr/share/elasticsearch/logs
......
- name: Create datadir for elasticsearch
  file:
    path: /usr/share/elasticsearch/data
....

**Comment by sadsfae** [comment]
Hey @elsharify I'm just using what Elastic sets as their defaults outlined here:

https://www.elastic.co/guide/en/elasticsearch/reference/2.0/setup-dir-layout.html

This can certainly be changed but you'd need to edit it in the playbook elastic search jinja2 template/config prior to deploying (Elastic looks for things in these locations unless told otherwise).

https://github.com/sadsfae/ansible-elk/blob/master/install/roles/elasticsearch/templates/elasticsearch.yml.j2

At this time I want to leave things as to what Elastic recommends as defaults, if this changes I'll change it here.  Perhaps one of the reasons for this is some folks (still, probably in older systems however) make `/var` a separate partition or it could be an LSB thing.  I don't really know why the default is what it is.

**Comment by yasirsharif** [comment]
Dear @sadsfae,
Sorry for late response.
The doc you have mentioned is an outdated document, the recent one is:
[https://www.elastic.co/guide/en/elasticsearch/reference/current/rpm.html#rpm-layout](https://www.elastic.co/guide/en/elasticsearch/reference/current/rpm.html#rpm-layout)
