### ISSUE TITLE
iptables_tcp5044_exists can be replaced with iptables_tcp{{logstash_syslog_port}}_exists

### ISSUE THREAD

**Issue by shuneguchi** [sadsfae/ansible-elk#8]
Please be aware of that this issue is harmless and can be overlook. I just wanted to share it since this playbook is super-nice ;)

In [install/roles/logstash/tasks/main.yml](../blob/master/install/roles/logstash/tasks/main.yml), Ansible checks if logstatsh syslog port was blocked by iptables.

``` yml
138 # iptables-services
139 - name: check firewall rules for TCP/{{logstash_syslog_port}} (iptables-services)
140   shell: grep "dport {{logstash_syslog_port}} \-j ACCEPT" /etc/sysconfig/iptables | wc -l
141   ignore_errors: true
142   register: iptables_tcp5044_exists
143   failed_when: iptables_tcp{{logstash_syslog_port}}_exists == 127
```

Here, although Ansible stores the value as `iptables_tcp5044_exists`, this registry is technically `iptables_tcp{{logstash_syslog_port}}_exists`.

Please consider to replace the registry name.

**Comment by sadsfae** [comment]
Thanks for noting this @ShunEguchi.  I had problems with Ansible properly performing the right multi-conditional check here:

https://github.com/sadsfae/ansible-elk/blob/master/install/roles/logstash/tasks/main.yml#L156

The issue is that if I used the variable `iptables_tcp{{logstash_syslog_port}}_exists` Ansible does not extrapolate that correctly to turn into `iptables_tcp5044_exists` on that last check, therefore I left it hard-coded as a workaround.

It could be a bug in Ansible or more likely I'm doing something wrong but it does not properly evaluate `iptables_tcp{{logstash_syslog_port}}_exists.stdout|int == 0` as a registered value.

It does elsewhere, hence the usage of proper {{ some_var_here }} in other places.

**Comment by shuneguchi** [comment]
Thanks for this comment, @sadsfae. Since this issue is harmless and can be ignored, I am going to close this out.
